### ISSUE TITLE
jvm 采集需要添加线程状态等相关指标

### ISSUE THREAD

**Issue by thelastant** [GuanceCloud/dd-trace-java#25]
目前支持的如下：
![image](https://user-images.githubusercontent.com/34938379/216304435-c6087712-0cc1-47a2-acfb-9b023aba5300.png)

期望目标：
<img width="622" alt="b76576e806066cfff62d5594a93d0eb5" src="https://user-images.githubusercontent.com/34938379/216304585-b031c49f-e97f-4b73-bdbc-83e9c7e8070f.png">

![image](https://user-images.githubusercontent.com/34938379/216304680-0a3abb1a-293b-4ea7-b9fb-c2058fe6d535.png)

**Comment by songlonqi-java** [comment]
## 如何通过ddtrace获得jvm线程指标
dd-java-agent 本身集成了 jmxfetch ，但是默认的线程指标只有一个：`jvm.thread_count` 

这时候 需要自定义配置文件和指标。

首先需要配置文件：
1. 创建文件夹 `/usr/local/ddtrace/conf.d` 目录随意（注意权限），下面用的着。
2. 在文件夹下创建配置文件 `guance.d/conf.yaml` , 文件必须是 yaml 格式。
3. conf.yaml 文件配置看最后。

java服务开启jmx，需要的启动参数为：
```shell
  -Ddd.jmxfetch.enabled=true\
  -Dcom.sun.management.jmxremote.host=127.0.0.1 \
  -Dcom.sun.manaagement.jmxremote.port=9012 \
  -Dcom.sun.management.jmxremote.ssl=false \
  -Dcom.sun.management.jmxremote.authenticate=false \
```

ddagent 需要增加启动参数：此处的配置对应上文的目录和文件
```shell
-javaagent:/usr/local/dd-java-agent.jar \
-Ddd.jmxfetch.config.dir="/usr/local/ddtrace/conf.d/" \
-Ddd.jmxfetch.config="guance.d/conf.yaml" \
```

我的服务名为 tmall.jar 合并启动参数为：
```shell
java -javaagent:/usr/local/dd-java-agent.jar \
  -Ddd.trace.debug=true\
  -Ddd.jmxfetch.enabled=true\
  -Dcom.sun.management.jmxremote.host=127.0.0.1 \
  -Dcom.sun.manaagement.jmxremote.port=9012 \
  -Dcom.sun.management.jmxremote.ssl=false \
  -Dcom.sun.management.jmxremote.authenticate=false \
  -Ddd.jmxfetch.config.dir="/usr/local/ddtrace/conf.d/" \
  -Ddd.jmxfetch.config="guance.d/conf.yaml" \
  -jar tmall.jar
```

conf.yaml 配置文件如下：
```yaml
init_config:
  is_jmx: true
  collect_default_metrics: true

instances:
  - jvm_direct: true
    host: localhost
    port: 9012
    conf: 
      - include:
          domain: java.lang
          type: Threading
          attribute:
            TotalStartedThreadCount:
              alias: jvm.total_thread_count
              metric_type: gauge
            PeakThreadCount:
              alias: jvm.peak_thread_count
              metric_type: gauge
            DaemonThreadCount:
              alias: jvm.daemon_thread_count
              metric_type: gauge
```

>  注意：java 服务必须开启 jmx 端口。
